TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
    "hostname 148 234 ${TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}"
)

TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
    "cpu_load 234 148 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}"
    "battery_vhud 234 148 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}"
    "date 234 148 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}"
    "time 234 148 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}"
)
